/**
 * ln(x) polynomial approximation adapter — atanh series form.
 *
 * Algorithm:
 *   Input x: fixed-point integer (×10000), e.g. 10000 = 1.0
 *   1. Range reduction: find k s.t. xr ∈ [10000, 20000)
 *   2. s = (xr - 10000) * 10000 / (xr + 10000)   →  s ∈ [0, 3333]
 *   3. ln(xr/10000) ≈ A1*s/SCALE + A3*s³/SCALE² + A5*s⁵/SCALE³
 *      (coefficients absorb the factor of 2; theoretical: A1=20000, A3=6667, A5=4000)
 *   4. ln(x/10000) = k * LN2 + ln(xr/10000)
 *
 * Intermediate overflow analysis (s ≤ 3333, SCALE = 10000):
 *   s²    = s*s    ≤ 11M   — fits int32 (max ~2.1B)
 *   s2    = s²/SCALE ≤ 1111
 *   s3    = s*s2   ≤ 3.7M  — fits int32
 *   s5    = s3*s2  ≤ 4.1M  — fits int32
 *   A1*s  ≤ 22000*3333 ≤ 73M — fits int32
 *   A3*s3 ≤ 7000*3703  ≤ 26M — fits int32
 *   A5*s5 ≤ 5000*4115  ≤ 21M — fits int32
 */

import { TunerAdapter, ParamSpec, ResultMeta } from '../types';
import { i32 } from '../simulator';

const SCALE = 10000;
const LN2_SCALED = 6931; // ln(2) * 10000

export const defaultParams: Record<string, number> = {
  A1: 20000,
  A3: 6667,
  A5: 4000,
};

export const lnPolynomialAdapter: TunerAdapter = {
  name: 'ln-polynomial',
  description: 'ln(x) atanh series approximation using fixed-point int32 arithmetic',

  params: [
    { name: 'A1', range: [18000, 22000], integer: true } as ParamSpec,
    { name: 'A3', range: [5000, 9000],   integer: true } as ParamSpec,
    { name: 'A5', range: [2000, 6000],   integer: true } as ParamSpec,
  ],

  simulate(input: number, params: Record<string, number>): number {
    const A1 = i32(params['A1']);
    const A3 = i32(params['A3']);
    const A5 = i32(params['A5']);

    let x = i32(input);
    if (x <= 0) return -2147483648;

    // Step 1: range reduction to [10000, 20000)
    let k = 0;
    while (x < 10000)  { x = i32(x * 2); k--; }
    while (x >= 20000) { x = i32(x / 2); k++; }

    // Step 2: s = (xr - SCALE) * SCALE / (xr + SCALE)
    const num = i32(i32(x - SCALE) * SCALE);
    const den = i32(x + SCALE);
    if (den === 0) return Infinity as unknown as number;
    const s = i32(num / den);  // s ∈ [0, 3333]

    // Step 3: atanh series  (overflow-safe, each power divided by SCALE)
    const s2 = i32(i32(s * s)  / SCALE);          // s²/SCALE    ∈ [0, 1111]
    const s3 = i32(i32(s * s2) / SCALE);          // s³/SCALE²   ∈ [0, 370]
    const s5 = i32(i32(s3 * s2) / SCALE);         // s⁵/SCALE⁴   ∈ [0, 41]

    const lnxr = i32(
      i32(A1 * s  / SCALE) +
      i32(A3 * s3 / SCALE) +
      i32(A5 * s5 / SCALE)
    );

    // Step 4: ln(x) = k*ln(2) + ln(xr)
    return i32(i32(k * LN2_SCALED) + lnxr);
  },

  reference(input: number): number {
    if (input <= 0) return -Infinity;
    return Math.log(input / SCALE) * SCALE;
  },

  sampleInputs(): number[] {
    const inputs: number[] = [];
    // logarithmic sampling from 0.01 to 100 (×10000: 100 to 1_000_000)
    const logMin = Math.log10(100);
    const logMax = Math.log10(1_000_000);
    const steps = 200;
    for (let i = 0; i <= steps; i++) {
      const v = logMin + (i / steps) * (logMax - logMin);
      inputs.push(Math.round(Math.pow(10, v)));
    }
    return inputs;
  },

  generateCode(params: Record<string, number>, meta: ResultMeta): string {
    const A1 = Math.round(params['A1']);
    const A3 = Math.round(params['A3']);
    const A5 = Math.round(params['A5']);
    return `// AUTO-GENERATED by redscript tune — DO NOT EDIT
// Adapter: ln-polynomial | Date: ${meta.tuneDate}
// max_error: ${meta.maxError.toFixed(6)} | mae: ${meta.mae.toFixed(6)} | estimated_cmds: ${meta.estimatedCmds}
// Run \`redscript tune --adapter ln-polynomial\` to regenerate
//
// atanh series coefficients (×10000 scale):
//   A1 = ${A1}  (theoretical 2×10000 = 20000)
//   A3 = ${A3}  (theoretical 2/3×10000 = 6667)
//   A5 = ${A5}  (theoretical 2/5×10000 = 4000)

fn ln(x: int): int {
    // Input x: fixed-point ×10000; returns ln(x/10000)×10000
    // Valid range: x ∈ [100, 1000000]  (0.01 ~ 100.0)
    // max_error: ${meta.maxError.toFixed(6)} (in ×10000 units, i.e. ${(meta.maxError / SCALE).toFixed(8)} in real units)

    let scale: int = ${SCALE};
    let ln2: int = ${LN2_SCALED};
    let A1: int = ${A1};
    let A3: int = ${A3};
    let A5: int = ${A5};

    // Step 1: range reduction — bring x into [scale, 2*scale)
    let xr: int = x;
    let k: int = 0;
    while xr < scale {
        xr = xr * 2;
        k = k - 1;
    }
    while xr >= scale * 2 {
        xr = xr / 2;
        k = k + 1;
    }

    // Step 2: s = (xr - scale) * scale / (xr + scale)
    let s: int = (xr - scale) * scale / (xr + scale);

    // Step 3: atanh series ln(xr/scale) ≈ A1*s + A3*s³ + A5*s⁵ (all /scale)
    let s2: int = s * s / scale;
    let s3: int = s * s2;
    let s5: int = s3 * s2;
    let lnxr: int = A1 * s / scale + A3 * s3 / scale + A5 * s5 / scale;

    // Step 4: ln(x) = k*ln(2) + ln(xr/scale)
    return k * ln2 + lnxr;
}
`;
  },
};
