/**
 * sqrt(x) Newton's method adapter — fixed-point ×10000 scale.
 *
 * Algorithm:
 *   Input x: fixed-point integer (×10000), e.g. 10000 = 1.0
 *   Target: return floor(sqrt(x/10000) * 10000)
 *
 *   1. If x <= 0, return 0
 *   2. Initial guess: g = x >> INIT_SHIFT  (default: x/2)
 *   3. Newton iteration: g = (g + x * 10000 / g) / 2, repeated N times
 *      (x * 10000 / g done in two steps to avoid int32 overflow)
 *   4. Return g
 *
 * Overflow analysis (x ≤ 2147483647, scale = 10000):
 *   Naive x * 10000 overflows int32 for x > 214748.
 *   Split: (x * 100) / (g / 100) ≈ x * 10000 / g — each step stays in int32.
 *
 * Parameters:
 *   N:          iteration count, range [4, 12], integer
 *   INIT_SHIFT: initial guess right shift, range [0, 3], integer (1 → x/2)
 */

import { TunerAdapter, ParamSpec, ResultMeta } from '../types';
import { i32 } from '../simulator';

const SCALE = 10000;

export const defaultParams: Record<string, number> = {
  N: 8,
  INIT_SHIFT: 1,
};

export const sqrtNewtonAdapter: TunerAdapter = {
  name: 'sqrt-newton',
  description: 'sqrt(x) Newton iteration using fixed-point int32 arithmetic (×10000 scale)',

  params: [
    { name: 'N',          range: [4, 12], integer: true } as ParamSpec,
    { name: 'INIT_SHIFT', range: [0, 3],  integer: true } as ParamSpec,
  ],

  simulate(input: number, params: Record<string, number>): number {
    const N          = Math.round(params['N']!);
    const INIT_SHIFT = Math.round(params['INIT_SHIFT']!);

    let x = i32(input);
    if (x <= 0) return 0;

    // Initial guess: x >> INIT_SHIFT
    let g = i32(x >> INIT_SHIFT);
    if (g === 0) g = 1; // guard against zero guess

    // Newton iterations: g = (g + x*SCALE/g) / 2
    // Overflow-safe: split x*SCALE/g as i32(x*100) / i32(g/100)
    for (let iter = 0; iter < N; iter++) {
      const gHalf  = i32(g / 100);
      if (gHalf === 0) break; // avoid div-by-zero
      const xdivg  = i32(i32(x * 100) / gHalf); // ≈ x * 10000 / g
      g = i32(i32(g + xdivg) / 2);
      if (g <= 0) { g = 1; break; }
    }

    return g;
  },

  reference(input: number): number {
    if (input <= 0) return 0;
    return Math.floor(Math.sqrt(input / SCALE) * SCALE);
  },

  sampleInputs(): number[] {
    const inputs: number[] = [];
    // Linear sampling for small values (0.0001 to 1.0)
    for (let i = 1; i <= 100; i++) {
      inputs.push(i);         // tiny values: 0.0001 to 0.01
    }
    // Logarithmic sampling from 1.0 to 1000.0 (×10000: 10000 to 10_000_000)
    const logMin = Math.log10(SCALE);
    const logMax = Math.log10(10_000_000);
    const steps = 150;
    for (let i = 0; i <= steps; i++) {
      const v = logMin + (i / steps) * (logMax - logMin);
      inputs.push(Math.round(Math.pow(10, v)));
    }
    // Also add exact perfect squares
    for (let k = 1; k <= 1000; k++) {
      inputs.push(k * k * SCALE);  // sqrt should be exact: k * SCALE
    }
    return inputs;
  },

  generateCode(params: Record<string, number>, meta: ResultMeta): string {
    const N          = Math.round(params['N']!);
    const INIT_SHIFT = Math.round(params['INIT_SHIFT']!);

    // Build the repeated Newton iteration lines
    const iterLines = [];
    for (let i = 0; i < N; i++) {
      iterLines.push(`    g = (g + g / 100 * 0 + x * 100 / (g / 100)) / 2;`);
    }

    // Actually, generate cleaner code using a helper expression
    // g = (g + x * SCALE / g) / 2  — but overflow-safe
    const iters = Array.from({ length: N }, (_, i) =>
      `    g = (g + x * 100 / (g / 100)) / 2;  // iteration ${i + 1}`
    ).join('\n');

    return `// AUTO-GENERATED by redscript tune — DO NOT EDIT
// Adapter: sqrt-newton | Date: ${meta.tuneDate}
// max_error: ${meta.maxError.toFixed(6)} | mae: ${meta.mae.toFixed(6)} | estimated_cmds: ${meta.estimatedCmds}
// Run \`redscript tune --adapter sqrt-newton\` to regenerate
//
// Parameters:
//   N          = ${N}   (Newton iteration count)
//   INIT_SHIFT = ${INIT_SHIFT}   (initial guess = x >> ${INIT_SHIFT})

fn sqrt_fx(x: int): int {
    // Input x: fixed-point ×10000, returns floor(sqrt(x/10000)*10000)
    // Valid range: x ∈ [0, 2147483647]
    // max_error: ${meta.maxError.toFixed(6)} (in ×10000 units)

    if (x <= 0) { return 0; }

    // Initial guess: x / ${1 << INIT_SHIFT}
    let g: int = x / ${1 << INIT_SHIFT};
    if (g <= 0) { g = 1; }

    // Newton iterations: g = (g + x * 10000 / g) / 2
    // Overflow-safe split: x * 10000 / g  →  x * 100 / (g / 100)
${iters}

    return g;
}
`;
  },
};
