/**
 * sqrt(x) Newton's method adapter — fixed-point ×10000 scale.
 *
 * Algorithm:
 *   Input x: fixed-point integer (×10000), e.g. 10000 = 1.0
 *   Target: return floor(sqrt(x/10000) * 10000)
 *
 *   1. If x <= 0, return 0
 *   2. Initial guess: g = x >> INIT_SHIFT  (default: x/2)
 *   3. Newton iteration: g = (g + x * 10000 / g) / 2, repeated N times
 *      Overflow-safe: x * 10000 / g  →  (x * 100) / (g / 100)
 *   4. Return g
 *
 * Valid range: x ∈ [1, 1_000_000]  (real range 0.0001 to 100.0)
 *   Larger x needs more iterations; beyond 1M, convergence is not guaranteed
 *   within N=12 iterations from an x/2 initial guess.
 *
 * Overflow analysis (x ≤ 1_000_000, SCALE = 10000):
 *   x * 100 ≤ 100_000_000 — fits int32 (max ~2.1B) ✓
 *   g / 100 is never 0 for g ≥ 100 (guard included) ✓
 *
 * Parameters:
 *   N:          iteration count, range [4, 12], integer
 *   INIT_SHIFT: initial guess right shift, range [0, 3], integer (1 → x/2)
 */

import { TunerAdapter, ParamSpec, ResultMeta } from '../types';
import { i32 } from '../simulator';

const SCALE = 10000;

export const defaultParams: Record<string, number> = {
  N: 8,
  INIT_SHIFT: 1,
};

export const sqrtNewtonAdapter: TunerAdapter = {
  name: 'sqrt-newton',
  description: 'sqrt(x) Newton iteration using fixed-point int32 arithmetic (×10000 scale)',

  params: [
    { name: 'N',          range: [4, 12], integer: true } as ParamSpec,
    { name: 'INIT_SHIFT', range: [0, 3],  integer: true } as ParamSpec,
  ],

  simulate(input: number, params: Record<string, number>): number {
    const N          = Math.round(params['N']!);
    const INIT_SHIFT = Math.round(params['INIT_SHIFT']!);

    let x = i32(input);
    if (x <= 0) return 0;

    // Initial guess: x >> INIT_SHIFT
    let g = i32(x >> INIT_SHIFT);
    if (g <= 0) g = 1; // guard against zero/negative guess

    // Newton iterations: g = (g + x * 10000 / g) / 2
    // Overflow-safe for x ≤ 1_000_000: split x*10000/g as (x*100)/(g/100)
    for (let iter = 0; iter < N; iter++) {
      const gDiv = i32(g / 100);
      if (gDiv <= 0) break; // guard: g is too small, stop
      const xdivg = i32(i32(x * 100) / gDiv); // ≈ x * 10000 / g
      g = i32(i32(g + xdivg) / 2);
      if (g <= 0) { g = 1; break; }
    }

    return g;
  },

  reference(input: number): number {
    if (input <= 0) return 0;
    return Math.floor(Math.sqrt(input / SCALE) * SCALE);
  },

  sampleInputs(): number[] {
    const inputs: number[] = [];

    // Logarithmic sampling from 0.01 to 100.0 (×10000: 100 to 1_000_000)
    // Lower bound 100 avoids g/100=0 in overflow-safe Newton step.
    const logMin = Math.log10(100);
    const logMax = Math.log10(1_000_000);
    const steps = 200;
    for (let i = 0; i <= steps; i++) {
      const v = logMin + (i / steps) * (logMax - logMin);
      const x = Math.round(Math.pow(10, v));
      inputs.push(x);
    }

    // Exact perfect squares (k=1..10 → x up to 100 * 10000 = 1_000_000)
    for (let k = 1; k <= 10; k++) {
      inputs.push(k * k * SCALE); // sqrt should be exactly k * SCALE
    }

    return inputs;
  },

  generateCode(params: Record<string, number>, meta: ResultMeta): string {
    const N          = Math.round(params['N']!);
    const INIT_SHIFT = Math.round(params['INIT_SHIFT']!);

    const iters = Array.from({ length: N }, (_, i) =>
      `    g = (g + x * 100 / (g / 100)) / 2;  // iteration ${i + 1}`
    ).join('\n');

    return `// AUTO-GENERATED by redscript tune — DO NOT EDIT
// Adapter: sqrt-newton | Date: ${meta.tuneDate}
// max_error: ${meta.maxError.toFixed(6)} | mae: ${meta.mae.toFixed(6)} | estimated_cmds: ${meta.estimatedCmds}
// Run \`redscript tune --adapter sqrt-newton\` to regenerate
//
// Parameters:
//   N          = ${N}   (Newton iteration count)
//   INIT_SHIFT = ${INIT_SHIFT}   (initial guess = x >> ${INIT_SHIFT}, i.e. x / ${1 << INIT_SHIFT})

fn sqrt_fx(x: int): int {
    // Input x: fixed-point ×10000, returns floor(sqrt(x/10000)*10000)
    // Valid range: x ∈ [0, 1000000]  (real range 0.0 to 100.0)
    // max_error: ${meta.maxError.toFixed(6)} (in ×10000 units)
    //
    // Overflow-safe: x*10000/g computed as (x*100)/(g/100), valid for x ≤ 1_000_000

    if (x <= 0) { return 0; }

    // Initial guess: x / ${1 << INIT_SHIFT}
    let g: int = x / ${1 << INIT_SHIFT};
    if (g <= 0) { g = 1; }

    // Newton iterations: g = (g + x * 10000 / g) / 2
    // Split to avoid overflow: (x * 100) / (g / 100) ≈ x * 10000 / g
${iters}

    return g;
}
`;
  },
};
